module.exports = [
  {
    id: 1,
    tipo: 'educativo',
    icone: '📱',
    titulo: 'Antes de sair de casa,\nmanda mensagem pra gente',
    subtexto: 'Consulte se o seu medicamento está disponível\npelo WhatsApp — rápido, sem fila, sem surpresa.',
    cta: '(51) 99469-7388',
  },
  {
    id: 2,
    tipo: 'educativo',
    icone: '💊',
    titulo: 'Sábado é dia de\nresolver o que ficou pra trás',
    subtexto: 'A Biopharma está aberta até as 18h\npara te atender no Centro Histórico.',
    cta: '(51) 99469-7388',
  },
  {
    id: 3,
    tipo: 'servico',
    icone: '💉',
    titulo: 'Aplicação de injetáveis\naqui na farmácia',
    subtexto: 'Sem precisar ir até uma clínica.\nAgende pelo WhatsApp.',
    cta: '(51) 99469-7388',
  },
  {
    id: 4,
    tipo: 'servico',
    icone: '💉',
    titulo: 'Você sabia que dá pra\ntomar sua injeção aqui?',
    subtexto: 'A Biopharma faz aplicação de injetáveis\nno Centro Histórico de Porto Alegre.',
    cta: '(51) 99469-7388',
  },
  {
    id: 5,
    tipo: 'educativo',
    icone: '🏙️',
    titulo: 'Trabalha no Centro\nde Porto Alegre?',
    subtexto: 'Passe na Biopharma na hora do almoço\nou depois do trabalho. Abertos até 20h.',
    cta: '(51) 99469-7388',
  },
  {
    id: 6,
    tipo: 'institucional',
    icone: '📍',
    titulo: 'Nos encontre no\nCentro Histórico de POA',
    subtexto: 'Av. Des. André da Rocha, 328\nSeg–Sex: 9h às 20h | Sáb: 9h às 18h',
    cta: '(51) 99469-7388',
  },
  {
    id: 7,
    tipo: 'educativo',
    icone: '⏰',
    titulo: 'Você toma remédio\nno horário certo?',
    subtexto: 'Medicamentos de uso contínuo funcionam melhor\nquando tomados sempre no mesmo horário.',
    cta: 'Dúvidas? (51) 99469-7388',
  },
  {
    id: 8,
    tipo: 'servico',
    icone: '🧣',
    titulo: 'O frio chegou —\ncuide da sua saúde',
    subtexto: 'Na Biopharma você encontra tudo para\npassar bem esse inverno.',
    cta: '(51) 99469-7388',
  },
  {
    id: 9,
    tipo: 'institucional',
    icone: '❤️',
    titulo: 'Farmácia de confiança\nno coração de Porto Alegre',
    subtexto: 'Medicamentos, higiene, beleza\ne aplicação de injetáveis em um só lugar.',
    cta: 'Av. Des. André da Rocha, 328',
  },
  {
    id: 10,
    tipo: 'educativo',
    icone: '🤝',
    titulo: 'Na Biopharma, você\nnão é só mais um cliente',
    subtexto: 'Atendimento próximo, sem pressa,\ncom atenção de verdade.',
    cta: '(51) 99469-7388',
  },
];
